#!/usr/bin/env node
// =============================================================================
// build.js — Concatenates ES module files into a single browser-ready IIFE
// Run: node build.js
// Output: app.bundle.js (loaded by index.html as a plain <script>)
// =============================================================================

import { readFileSync, writeFileSync } from 'fs';

// Order matters: dependencies must come before dependents
const files = [
  'js/constants.js',
  'js/taxBrackets.js',
  'js/state.js',
  'js/prettyPrinter.js',
  'js/calculator.js',
  'js/serializer.js',
  'js/uiConstants.js',
  'js/appState.js',
  'js/renderer.js',
  'js/modalController.js',
  'js/eventHandlers.js',
];

function stripImportsExports(code) {
  // Remove import lines
  code = code.replace(/^\s*import\s+.*?from\s+['"].*?['"];?\s*$/gm, '');
  code = code.replace(/^\s*import\s+['"].*?['"];?\s*$/gm, '');
  // Remove export keywords (keep the declarations)
  code = code.replace(/^\s*export\s+(function|const|let|var|class)\s/gm, '$1 ');
  code = code.replace(/^\s*export\s+\{[^}]*\};?\s*$/gm, '');
  code = code.replace(/^\s*export\s+default\s+/gm, '');
  return code;
}

let bundle = '// Auto-generated by build.js — do not edit\n';
bundle += '(function() {\n"use strict";\n\n';

for (const file of files) {
  const raw = readFileSync(file, 'utf8');
  const cleaned = stripImportsExports(raw);
  bundle += `// --- ${file} ---\n${cleaned}\n\n`;
}

// Expose onclick-referenced functions as globals
bundle += '// Expose globals for onclick handlers\n';
bundle += 'window.initiateDelete = initiateDelete;\n';
bundle += 'window.confirmDelete = confirmDelete;\n';
bundle += 'window.cancelDelete = cancelDelete;\n';
bundle += 'window.openEditModal = openEditModal;\n';

bundle += '\n})();\n';

writeFileSync('app.bundle.js', bundle, 'utf8');
console.log('Built app.bundle.js (' + bundle.length + ' bytes)');
